# Generated by Django 3.0.7 on 2020-07-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='submit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.Account'),
        ),
    ]
