# Generated by Django 3.0.7 on 2020-07-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_auto_20200712_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
