# Generated by Django 3.0.7 on 2020-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0003_remove_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contactEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='contactNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
