# Generated by Django 3.0.7 on 2020-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0004_auto_20200712_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contactEmail',
        ),
        migrations.AddField(
            model_name='account',
            name='contactWhastappNo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
