# Generated by Django 3.0.7 on 2020-07-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0005_auto_20200712_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contactWhastappNo',
            new_name='contactWhatsappNo',
        ),
    ]
