# Generated by Django 3.0.7 on 2020-07-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0006_auto_20200712_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agencyName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
