# Generated by Django 3.0.8 on 2020-07-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0007_account_agencyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='agencyName',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contactNo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contactWhatsappNo',
        ),
        migrations.AddField(
            model_name='rent',
            name='acquire_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='dur_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='requirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='images',
            field=models.ManyToManyField(to='mainapi.Product_images'),
        ),
    ]
