# Generated by Django 3.0.8 on 2020-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0013_auto_20200725_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
