# Generated by Django 3.0.8 on 2020-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0015_auto_20200725_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='condition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='delivery_company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='from_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='instock',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='negotiable',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='payment_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='store_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='to_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='with_delivery',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
