# Generated by Django 3.0.8 on 2020-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0016_auto_20200731_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='likes',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
