# Generated by Django 3.0.8 on 2020-08-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0017_rent_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='store_name',
        ),
    ]
