# Generated by Django 3.0.8 on 2020-08-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0018_remove_rent_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
