# Generated by Django 3.0.8 on 2020-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0020_auto_20200810_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='issue',
            field=models.TextField(null=True),
        ),
    ]
