# Generated by Django 3.0.8 on 2020-08-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0021_rent_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rate',
        ),
        migrations.AddField(
            model_name='account',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
