# Generated by Django 3.0.8 on 2020-08-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0023_auto_20200814_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
