# Generated by Django 3.0.8 on 2020-08-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0026_auto_20200814_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='from_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
