# Generated by Django 3.0.8 on 2020-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0030_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='whatsapp_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
