# Generated by Django 3.0.8 on 2020-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0031_rent_whatsapp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
