# Generated by Django 3.0.8 on 2020-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0033_rent_exchange_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='acquire_type',
            field=models.CharField(default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='condition',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
